spring:
  h2:
    console:
      enabled: true
      path: /testdb
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: test
    passwored: test
  security:
    user:
      name: admin
      password: test
      role: admin